# Roll No: 2022CS63 , 2022CS75

import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

chrome_driver_path = 'C:/DSA/Scraping Mid Project/chromedriver-win64/chromedriver.exe'
service = Service(chrome_driver_path)
driver = webdriver.Chrome(service=service)

Names = []
Prices = []
Descriptions = []
Ratings = []
NoOFReviews = []
DiscountedPrice = []
Delivery = []
DiscountedPercent = []

def ScrapData2(end, URL1,URL2, boxtag, boxclass, nametag, nameclass, pricetag, priceclass, destag, desclass, ratingtag, raatingclass, noofrevtag, noofreviewsclass, discptag, dispclass, delivtag, delivclass,perctag,percclass):
    for i in range(1, end + 1):
        # Include the page number in the URL
        current_page_url = f"{URL1}{i}{URL2}"
        print(f"Scraping page {i}: {current_page_url}")  # Print the current page number
        driver.get(current_page_url)
        mainfunc(i,driver, boxtag, boxclass, nametag, nameclass, pricetag, priceclass, destag, desclass, ratingtag, raatingclass, noofrevtag, noofreviewsclass, discptag, dispclass, delivtag, delivclass,perctag,percclass)


def Scrapdata(end, URL, boxtag, boxclass, nametag, nameclass, pricetag, priceclass, destag, desclass, ratingtag, raatingclass, noofrevtag, noofreviewsclass, discptag, dispclass, delivtag, delivclass,perctag,percclass):
    for i in range(1, end + 1):
        # Include the page number in the URL
        current_page_url = f"{URL}{i}"
        print(f"Scraping page {i}: {current_page_url}")  # Print the current page number
        driver.get(current_page_url)
        mainfunc(i,driver, boxtag, boxclass, nametag, nameclass, pricetag, priceclass, destag, desclass, ratingtag, raatingclass, noofrevtag, noofreviewsclass, discptag, dispclass, delivtag, delivclass,perctag,percclass)


def mainfunc(i,driver, boxtag, boxclass, nametag, nameclass, pricetag, priceclass, destag, desclass, ratingtag, raatingclass, noofrevtag, noofreviewsclass, discptag, dispclass, delivtag, delivclass,perctag,percclass):
    content = driver.page_source
    soup = BeautifulSoup(content, 'lxml')

    for a in soup.findAll(boxtag, attrs={'class': boxclass}):
        names = a.find(nametag, attrs={'class': nameclass})
        price = a.find(pricetag, attrs={'class': priceclass})
        descriptions = a.find(destag, attrs={'class': desclass})
        ratings = a.find(ratingtag, attrs={'class': raatingclass})
        noofreviews = a.find(noofrevtag, attrs={'class': noofreviewsclass})
        discounntedprices = a.find(discptag, attrs={'class': dispclass})
        deliverys = a.find(delivtag, attrs={'class': delivclass})
        discountedpercent = a.find(perctag, attrs={'class': percclass})

        # Extracting text or printing 'null' if attribute is missing
        Names.append(names.get_text() if names else 'null')
        Prices.append(price.get_text() if price else 'null')
        Descriptions.append(descriptions.get_text() if descriptions else 'null')
        Ratings.append(ratings.get_text() if ratings else 'null')
        NoOFReviews.append(noofreviews.get_text() if noofreviews else 'null')
        DiscountedPrice.append(discounntedprices.get_text() if discounntedprices else 'null')
        Delivery.append(deliverys.get_text() if deliverys else 'null')
        DiscountedPercent.append(discountedpercent.get_text() if discountedpercent else 'null')


# Provide the correct URL pattern without HTML encoded ampersand
ScrapData2(102,"https://www.daraz.pk/catalog/?_keyori=ss&from=search_history&page=","&q=mobile%20phones&spm=a2a0e.home.search.1.35e34076Nm9UrT&sugg=mobile%20phones_0_1",'div','ant-col-20 ant-col-push-4 side-right--Tyehf','div','title--wFj93','span','currency--GVKjl','div','title--wFj93','div','rating--ZI3Ol rate--DCc4j','span','rating__review--ygkUy','span','origPrice--AJxRs','span','location--eh0Ro ',"span","discount--HADrg")
ScrapData2(25, "https://www.walmart.com/search?q=all+laptops&amp;typeahead=laptops&amp;page=","&amp;affinityOverride=default","div","relative w-80","span","w_V_DM","div","mr1 mr2-xl b black green lh-copy f5 f4-l","div","mv2","span","w_iUH7","span","sans-serif gray f7","div","gray mr1 strike f6 f4-l flex items-end mt1","div","mv2","span","f6 f5-l")
ScrapData2(40, "https://www.ebay.com/sch/i.html?_from=R40&_nkw=mobile+phones&_sacat=0&LH_TitleDesc=0&_sop=12&_ipg=240&_pgn=","&rt=nc","div","srp-main-content clearfix srp-main-content--flex","div","s-item__title","span","s-item__price","span","s-item__gsp-info s-item__gspInfo","span","clipped","span","s-item__reviews-count","span","STRIKETHROUGH","span","s-item__location s-item__itemLocation","span","s-item__discount s-item__discount")
ScrapData2(35, "https://www.ebay.com/sch/i.html?_from=R40&_nkw=electronics&_sacat=0&LH_TitleDesc=0&_sop=12&_ipg=60&_pgn=","&rt=nc","body","s-page no-touch skin-large srp--list-view srp-control-bar-redesign srp-expanded-list-view gh-flex","div","s-item__title","div","s-item__detail s-item__detail--primary","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")

# ALI BABA

Scrapdata(100,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.1c726533W1qwD5&fsb=y&IndexArea=product_en&keywords=laptops&tab=all&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Mobiles
Scrapdata(63,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.4a372277OQ1rgd&amp;fsb=y&amp;IndexArea=product_en&amp;keywords=mobiles&amp;tab=all&amp;&amp;page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Ipad
Scrapdata(63,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.873e75f7FwCQXr&fsb=y&IndexArea=product_en&keywords=ipad&tab=all&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Home appliances
Scrapdata(63,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.78a62ffdcu6hqs&fsb=y&IndexArea=product_en&keywords=home+appliances&tab=all&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Health care
Scrapdata(63,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.638a3f00MVVzTh&fsb=y&IndexArea=product_en&keywords=life+care&tab=all&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Kitchen appliances
Scrapdata(63,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.6dfa3e48aDtlzp&fsb=y&IndexArea=product_en&keywords=kitchen+appliances&tab=all&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Kitchen utensils
Scrapdata(45,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.77a0e857Tj8jyq&fsb=y&IndexArea=product_en&keywords=kitchen+appliances+and+utensils&tab=all&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# kitchen utensils and house hold appliances
Scrapdata(10,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.65255d0coVXdFI&fsb=y&IndexArea=product_en&keywords=kitchen+utensils+and+house+hold+appliances&tab=all&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Kitchen
Scrapdata(2,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.39cc590cEIVOHK&fsb=y&IndexArea=product_en&keywords=kitchen+utensils+and+house+hold+appliances+glasses&tab=all&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Fridge
Scrapdata(63,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.49ac3fa7UP3lmJ&fsb=y&IndexArea=product_en&keywords=fridge&tab=all&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto lightening system
Scrapdata(80,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.8414e0fcCLLluR&fsb=y&IndexArea=product_en&categoryId=127666031&keywords=Auto+Lighting+Systems&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Train part
Scrapdata(9,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.691e6625VHqDGD&fsb=y&IndexArea=product_en&categoryId=1206&keywords=Train+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Universal parts
Scrapdata(80,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.59ad24beMCmVwy&fsb=y&IndexArea=product_en&categoryId=1215&keywords=Universal+Parts&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Railway parts and accessories
Scrapdata(2,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.5a6c3025E8Y3Zr&fsb=y&IndexArea=product_en&categoryId=1239&keywords=Railway+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Engine parts
Scrapdata(10,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.6443779ejFD4qn&fsb=y&IndexArea=product_en&categoryId=127668037&keywords=New+Energy+Vehicle+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-m-product-features-list","div","search-card-e-price-main")
# Cooling System
Scrapdata(81,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.ee2449526mpiIB&fsb=y&IndexArea=product_en&categoryId=127684042&keywords=Cooling+System&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto Performance Parts
Scrapdata(81,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.2cac30427UzJqZ&fsb=y&IndexArea=product_en&categoryId=127684033&keywords=Auto+Performance+Parts&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Motorcycle Parts & Accessories
Scrapdata(81,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.471fd272aFsTpW&fsb=y&IndexArea=product_en&categoryId=3406&keywords=Motorcycle+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto Transmission Systems
Scrapdata(81,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.105c18d5lOMmaH&fsb=y&IndexArea=product_en&categoryId=100010935&keywords=Auto+Transmission+Systems&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Go-Kart & Kart Racer Parts & Accessories
Scrapdata(1,"https://www.alibaba.com/trade/search?spm=a27aq.cp_34.5837883380.10.a62d3aa6R2JxZ2&categoryId=127686029&SearchText=Go-Kart+%26+Kart+Racer+Parts+%26+Accessories&indexArea=product_en&fsb=y","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Air Conditioning Systems
Scrapdata(81,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.197171a2Nj9GzO&fsb=y&IndexArea=product_en&categoryId=127686030&keywords=Air+Conditioning+Systems&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto Steering Systems
Scrapdata(81,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.66684c84rbyfOr&fsb=y&IndexArea=product_en&categoryId=127672036&keywords=Auto+Steering+Systems&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto Electrical Systems
Scrapdata(75,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.7c4a4302nh92Sj&fsb=y&IndexArea=product_en&categoryId=127838001&keywords=Auto+Electrical+Systems&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto Drive Systems
Scrapdata(1,"https://alibaba.com/trade/search?spm=a27aq.cp_34.5837883380.14.a62d3aa6R2JxZ2&categoryId=100001052&SearchText=Auto+Drive+Systems&indexArea=product_en&fsb=y","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Bus Parts & Accessories
Scrapdata(40,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.72274df91uxTDC&fsb=y&IndexArea=product_en&categoryId=127674039&keywords=Bus+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Marine Parts & Accessories
Scrapdata(81,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.da353e90szRtQK&fsb=y&IndexArea=product_en&categoryId=100001648&keywords=Marine+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# ATV/UTV Parts & Accessories
Scrapdata(81,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.47f97ebfI6AA63&fsb=y&IndexArea=product_en&categoryId=100001610&keywords=ATV%2FUTV+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Heavy Duty Vehicle Parts & Accessories
Scrapdata(2,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.7ca576029XwkUM&fsb=y&IndexArea=product_en&categoryId=127690033&keywords=Heavy+Duty+Vehicle+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Container Parts & Accessories
Scrapdata(8,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.54014505bLEloo&fsb=y&IndexArea=product_en&categoryId=190000191&keywords=Container+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Heavy Duty Vehicle Parts & Accessories
Scrapdata(2,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.773b7602ej3JmK&fsb=y&IndexArea=product_en&categoryId=127690033&keywords=Heavy+Duty+Vehicle+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto Body Systems
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.27803bbe1iDdS8&fsb=y&IndexArea=product_en&categoryId=127840001&keywords=Auto+Body+Systems&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Truck Parts & Accessories
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.4cfd5991WfF75g&fsb=y&IndexArea=product_en&categoryId=127658034&keywords=Truck+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Aviation Parts & Accessories
Scrapdata(1,"https://www.alibaba.com/trade/search?spm=a27aq.cp_34.5837883380.23.a62d3aa62WAT7C&categoryId=127658032&SearchText=Aviation+Parts+%26+Accessories&indexArea=product_en&fsb=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Aviation Parts & Accessories
Scrapdata(1,"https://www.alibaba.com/trade/search?spm=a27aq.cp_34.5837883380.23.a62d3aa62WAT7C&categoryId=127658032&SearchText=Aviation+Parts+%26+Accessories&indexArea=product_en&fsb=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Trailer Parts & Accessories
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.55df95e1cX2EBT&fsb=y&IndexArea=product_en&categoryId=100005315&keywords=Trailer+Parts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto Brake Systems
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.42b26e5c6HrT1v&fsb=y&IndexArea=product_en&categoryId=127658031&keywords=Auto+Brake+Systems&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto Suspension Systems
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.7ef84802ulaSS1&fsb=y&IndexArea=product_en&categoryId=127664038&keywords=Auto+Suspension+Systems&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Auto Engine Systems
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.a157291c8ZDGEx&fsb=y&IndexArea=product_en&categoryId=127842001&keywords=Auto+Engine+Systems&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Other Auto Parts
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.edd6245cLKKtLw&fsb=y&IndexArea=product_en&categoryId=100004517&keywords=Other+Auto+Parts&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Smart Home Appliances
Scrapdata(71,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.65207b8aZ05Nkw&fsb=y&IndexArea=product_en&categoryId=201756204&keywords=Smart+Home+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Other Home Appliances
Scrapdata(6,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.28935f4abRiujT&fsb=y&IndexArea=product_en&categoryId=628&keywords=Other+Home+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Cleaning Appliances
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.2c7130f4sNwKKi&fsb=y&IndexArea=product_en&categoryId=201607803&keywords=Cleaning+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Major Kitchen Appliances
Scrapdata(15,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.390a5f9bJrM1vg&fsb=y&IndexArea=product_en&categoryId=201326902&keywords=Major+Kitchen+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Second-hand Appliances
Scrapdata(1,"https://www.alibaba.com/trade/search?spm=a27aq.cp_6.5999513210.21.34872a9ayCt3Ut&categoryId=201743901&SearchText=Second-hand+Appliances&indexArea=product_en&fsb=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Refrigerators & Freezers
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.79294afdQhKwUv&fsb=y&IndexArea=product_en&categoryId=100000136&keywords=Refrigerators+%26+Freezers&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Air Quality Appliances
Scrapdata(45,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.65052cfdldOvs8&fsb=y&IndexArea=product_en&categoryId=100000037&keywords=Air+Quality+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Heating & Cooling Appliances
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.5ed51b16LkdPrw&fsb=y&IndexArea=product_en&categoryId=100000040&keywords=Heating+%26+Cooling+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Laundry Appliances
Scrapdata(63,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.2a176ecbx2Pxia&fsb=y&IndexArea=product_en&categoryId=100000042&keywords=Laundry+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Small Kitchen Appliances
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.7f215cc30BCuVs&fsb=y&IndexArea=product_en&categoryId=100000041&keywords=Small+Kitchen+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Water Treatment Appliances
Scrapdata(55,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.568e1c82Hakuov&fsb=y&IndexArea=product_en&categoryId=100000044&keywords=Water+Treatment+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Personal Care & Beauty Appliances
Scrapdata(35,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.329297bdOMaFhx&fsb=y&IndexArea=product_en&categoryId=200540008&keywords=Personal+Care+%26+Beauty+Appliances&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Water Heater
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.43796043kNevJG&fsb=y&IndexArea=product_en&categoryId=100000043&keywords=Water+Heaters&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Belts & Accessories
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.6a7967beS1Kp46&fsb=y&IndexArea=product_en&categoryId=32801&keywords=Belts+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Wedding Apparel & Accessories
Scrapdata(17,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.9c3f68c2aUlb30&fsb=y&IndexArea=product_en&categoryId=320&keywords=Wedding+Apparel+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Gloves & Mittens
# Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.2208282dR4oxNK&fsb=y&IndexArea=product_en&categoryId=324&keywords=Gloves+%26+Mittens&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Scarves & Shawls
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.6638566f5r41Ve&fsb=y&IndexArea=product_en&categoryId=325&keywords=Scarves+%26+Shawls&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Ties & Accessories
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.562d1a73j0D7D8&fsb=y&IndexArea=product_en&categoryId=326&keywords=Ties+%26+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Clothes Accessories
Scrapdata(5,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.7d736e4151hXAj&fsb=y&IndexArea=product_en&categoryId=201756302&keywords=Clothes+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Novelty & Special Use
Scrapdata(30,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.54d4705bfDFusJ&fsb=y&IndexArea=product_en&categoryId=127726319&keywords=Novelty+%26+Special+Use&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Hats & Caps
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.323a64b1UCp3oh&fsb=y&IndexArea=product_en&categoryId=327&keywords=Hats+%26+Caps&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Other Fashion Accessories
Scrapdata(5,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.5a0573c8gsRVYn&fsb=y&IndexArea=product_en&categoryId=200770004&keywords=Other+Fashion+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Garment & Processing Accessories
Scrapdata(81,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.358e4f11ao4xLT&fsb=y&IndexArea=product_en&categoryId=127726322&keywords=Garment+%26+Processing+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Ethnic Accessories
Scrapdata(15,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.7afb4a39PN07ej&fsb=y&IndexArea=product_en&categoryId=201757101&keywords=Ethnic+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Ethnic Clothing
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.eaca537fpKuXGq&fsb=y&IndexArea=product_en&categoryId=201756701&keywords=Ethnic+Clothing&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Men's Clothing
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.2d33486fRNd7Zi&fsb=y&IndexArea=product_en&categoryId=127726318&keywords=Men%27s+Clothing&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Hair Accessories
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.324d280cwmuy7G&fsb=y&IndexArea=product_en&categoryId=33901&keywords=Hair+Accessories&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Jewelry
Scrapdata(84,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.691154e2KAr3lJ&fsb=y&IndexArea=product_en&categoryId=1509&keywords=Jewelry&&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Watches
Scrapdata( 1,"https://www.alibaba.com/trade/search?spm=a27aq.cp_36.8392820710.3.7f25502aujlqHG&categoryId=1511&SearchText=Watches&indexArea=product_en&fsb=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Eye wear
Scrapdata( 1,"https://www.alibaba.com/trade/search?spm=a27aq.cp_36.8392820710.4.7f25502aujlqHG&categoryId=1512&SearchText=Eyewear&indexArea=product_en&fsb=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
# Eyewear Accessories
Scrapdata( 1,"https://www.alibaba.com/trade/search?spm=a2700.galleryofferlist.0.0.38985594dtAbWD&fsb=y&IndexArea=product_en&categoryId=127726042&keywords=Eyewear+Accessories&page=","div","app-organic-search__main-body","h2","search-card-e-title","div","search-card-e-price-main","div","search-card-m-sale-features__item","span","search-card-e-review","span","search-card-e-review","div","search-card-e-price-main","span","search-card-e-sell-point","div","search-card-e-price-main")
Scrapdata(100,"https://www.alibaba.com/trade/search?fsb=y&IndexArea=product_en&keywords=mobile+phones&tab=all&&page=","div","app-organic-search l-main-wrap J-p4p-container","h2","search-card-e-title","div","search-card-e-price-main","h2","search-card-e-title","span","search-card-e-review","span","search-card-e-review","span","search-card-e-price__original","div","search-card-m-action-gallery search-card-m-action-area action-area-layout__horizontal","span","search-card-e-price__discount")
Scrapdata(45, "https://www.amazon.com/s?k=mobile+phones&amp;page=2&amp;crid=3JCDMELDZ24XJ&amp;qid=1697004182&amp;sprefix=MOBILE%2Caps%2C310&amp;ref=sr_pg_","div","sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16","div","a-section a-spacing-none s-title-instructions-style","span","a-price","span","a-size-small a-color-base a-text-normal","span","a-size-mini","span","a-size-mini a-color-base puis-light-weight-text","span","a-offscreen","div","a-row a-size-small a-color-secondary","span","a-offscreen")
Scrapdata(45, "https://www.amazon.com/s?k=laptop+computer&page=&crid=1085HBL7DT5J1&qid=1697005700&sprefix=lap%2Caps%2C987&ref=sr_pg_","div","sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16","h2","a-size-mini a-spacing-none a-color-base s-line-clamp-2","span","a-offscreen","span","a-size-medium a-color-base a-text-normal","span","a-icon-alt","span","a-size-base s-underline-text","span","a-offscreen","div","a-row a-size-base a-color-secondary s-align-children-center","span","a-size-base a-color-secondary")

# FLIPKART
#
Scrapdata(45, "https://www.flipkart.com/search?q=mobiles&as=on&as-show=on&otracker=AS_Query_TrendingAutoSuggest_1_0_na_na_na&otracker1=AS_Query_TrendingAutoSuggest_1_0_na_na_na&as-pos=1&as-type=TRENDING&suggestionId=mobiles&requestId=0dbbf0e0-bd6f-462f-b0c1-6abc15439d84&page=","div","_1AtVbE","div","_4rR01T","div","_30jeq3","ul","_1xgFaf","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
Scrapdata(25, "https://www.flipkart.com/search?q=all+laptops&otracker=AS_Query_HistoryAutoSuggest_2_0&otracker1=AS_Query_HistoryAutoSuggest_2_0&marketplace=FLIPKART&as-show=on&as=off&as-pos=2&as-type=HISTORY&page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
Scrapdata(40, "https://www.flipkart.com/search?q=washing+machine&amp%3Bsid=j9e%2Cabm%2C8qx&amp%3Bas=on&amp%3Bas-show=on&amp%3Botracker=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&amp%3Botracker1=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&amp%3Bas-pos=1&amp%3Bas-type=RECENT&amp%3BsuggestionId=washing+machine%7CWashing+Machines&amp%3BrequestId=caca9d67-1a96-4bbb-9a54-f2bb17fc12a1&amp%3Bas-backfill=on&amp%3Bpage=3&page=","div","_1YokD2 _3Mn1Gg","div","_4rR01T","div","_30jeq3 _1_WHN1","div","fMghEO","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc _27UcVY","div","_2Tpdn3","div","_3Ay6Sb")
Scrapdata(25, "https://www.flipkart.com/search?q=smart+watch&as=on&as-show=on&otracker=AS_Query_HistoryAutoSuggest_1_5_na_na_na&otracker1=AS_Query_HistoryAutoSuggest_1_5_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=smart+watch&requestId=23f109e4-50b7-4ce2-8959-b26b0f38a5e7&as-searchtext=smart+&page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_3eWWd-","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
Scrapdata(25, " https://www.flipkart.com/gaming/pr?sid=4rr&fm=neo%2Fmerchandising&iid=M_a5ecccb3-fb99-4893-916c-7d5753ea57b2_1_372UD5BXDFYS_MC.T6Z44HHCR56C&otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Electronics~Gaming~All_T6Z44HHCR56C&otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&cid=T6Z44HHCR56C=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu-","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
Scrapdata(25, "https://www.flipkart.com/search?q=speaker&sid=0pm%2C0o7&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_3_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_3_na_na_na&as-pos=1&as-type=RECENT&suggestionId=speaker%7CSpeakers&requestId=b85685fb-8539-4866-bcc1-59c9a69eee7e&as-backfill=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu-","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
Scrapdata(20, "https://www.flipkart.com/search?q=all+laptops&otracker=AS_Query_HistoryAutoSuggest_2_0&otracker1=AS_Query_HistoryAutoSuggest_2_0&marketplace=FLIPKART&as-show=on&as=off&as-pos=2&as-type=HISTORY&page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
Scrapdata(20, "https://www.flipkart.com/search?q=smart+watch&amp;sid=ajy%2Cbuh&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_2_1_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_2_1_na_na_na&amp;as-pos=2&amp;as-type=RECENT&amp;suggestionId=smart+watch%7CSmart+Watches&amp;requestId=78837c2f-4aeb-4ce7-9168-fca1bcc992f6&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_3eWWd-","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
#Washing Machine
Scrapdata(40, "https://www.flipkart.com/search?q=washing+machine&amp;sid=j9e%2Cabm%2C8qx&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=washing+machine%7CWashing+Machines&amp;requestId=caca9d67-1a96-4bbb-9a54-f2bb17fc12a1&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","div","_4rR01T","div","_30jeq3 _1_WHN1","div","fMghEO","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc _27UcVY","div","_2Tpdn3","div","_3Ay6Sb")
#FRIDGE
Scrapdata(40, "https://www.flipkart.com/search?q=refrigerator&amp;as=on&amp;as-show=on&amp;otracker=AS_Query_OrganicAutoSuggest_3_3_na_na_na&amp;otracker1=AS_Query_OrganicAutoSuggest_3_3_na_na_na&amp;as-pos=3&amp;as-type=RECENT&amp;suggestionId=refrigerator&amp;requestId=dce5c2d7-ea69-4656-90b1-6255b1e452e9&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","div","_4rR01T","div","_30jeq3 _1_WHN1","div","fMghEO","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc _27UcVY","div","_2Tpdn3","div","_3Ay6Sb")
Scrapdata(25, "https://www.flipkart.com/search?q=speaker&amp;sid=0pm%2C0o7&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_5_3_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_5_3_na_na_na&amp;as-pos=5&amp;as-type=HISTORY&amp;suggestionId=speaker%7CSpeakers&amp;requestId=b85685fb-8539-4866-bcc1-59c9a69eee7e&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
Scrapdata(25, "https://www.flipkart.com/search?q=+oven&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3 _18hQoS","div","_3Ay6Sb")
Scrapdata(40, "https://www.flipkart.com/search?q=fans&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=off&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","div","_4rR01T","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3 _18hQoS","div","_3Ay6Sb")
#LIGHTS
Scrapdata(25, "https://www.flipkart.com/search?q=lights&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3 _18hQoS","div","_3Ay6Sb")
#MEDICAL DEVICES
Scrapdata(25, "https://www.flipkart.com/search?q=medical+devices&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
#PRINTERS
Scrapdata(8, "https://www.flipkart.com/search?q=printer&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=off&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# TOYS
Scrapdata(25, "https://www.flipkart.com/search?q=toys&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_3Ay6Sb","div","_3Ay6Sb")
# IPADS
Scrapdata(15, "https://www.flipkart.com/search?q=ipads&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=off&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","div","_4rR01T","div","_30jeq3 _1_WHN1","ul","_1xgFaf","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc _27UcVY","div","_2Tpdn3","div","_3Ay6Sb")
# GAMES
Scrapdata(25, "https://www.flipkart.com/search?q=games&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Medicine
Scrapdata(40, "https://www.flipkart.com/search?q=medicines&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=off&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# AC
Scrapdata(21, "https://www.flipkart.com/search?q=ac+1.5+ton&amp;sid=j9e%2Cabm%2Cc54&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_2_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_2_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=ac+1.5+ton%7CAir+Conditioners&amp;requestId=59e5d1cd-1b7b-4560-b7dc-cabd11fd238e&amp;page=","div","_1YokD2 _3Mn1Gg","div","_4rR01T","div","_30jeq3 _1_WHN1","ul","_1xgFaf","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc _27UcVY","div","_2Tpdn3","div","_3Ay6Sb")
# Chairs
Scrapdata(25, "https://www.flipkart.com/search?q=chairs&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Tables
Scrapdata(40, "https://www.flipkart.com/search?q=tables&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Projectors
Scrapdata(13, "https://www.flipkart.com/search?q=projectors&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=off&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women Dresses
Scrapdata(22, "https://www.flipkart.com/search?q=women+dress&amp;sid=clo%2Codx%2Cmaj%2Cjhy&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_2_5_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_2_5_na_na_na&amp;as-pos=2&amp;as-type=RECENT&amp;suggestionId=women+dress%7CWomen%27s+Dresses&amp;requestId=afda6adc-00d4-46ea-b134-80d99b073ce3&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","div","_2WkVRV","div","_30jeq3","a","IRpwTa","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Crcokery
Scrapdata(12, "https://www.flipkart.com/search?q=crockery+dinner+set&amp;sid=upp%2Ci7t%2Clha&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_5_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_5_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=crockery+dinner+set%7CDinner+Sets&amp;requestId=1468fd1a-8081-4a0d-8031-1e241d683e27&amp;as-searchtext=crock&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Kitchen Utensils
Scrapdata(25, "https://www.flipkart.com/search?q=kitchen+items&amp;sid=upp%2C5ix&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=kitchen+items%7CKitchen+Storage+%26+Containers&amp;requestId=8918e0e2-bed7-4a4b-874e-26de511c19db&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Beauty Products
Scrapdata(25, "https://www.flipkart.com/search?q=beauty+products&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;as-pos=1&amp;as-type=HISTORY&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Grocery Products
Scrapdata(25, "https://www.flipkart.com/search?q=grocery+products&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Decorative Items
Scrapdata(25, "https://www.flipkart.com/search?q=decoration+items&amp;sid=arb%2Ca77&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_na&amp;as-pos=2&amp;as-type=RECENT&amp;suggestionId=decoration+items%7CWall+Decor+Items&amp;requestId=ec40c499-372e-48a1-a636-9564a09c41b6&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3 _18hQoS","div","_3Ay6Sb")
# Shoes
Scrapdata(25, "https://www.flipkart.com/search?q=shoes&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=2","div","_1YokD2 _3Mn1Gg","div","_2WkVRV","div","_30jeq3","a","IRpwTa","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3 _18hQoS","div","_3Ay6Sb")
# IRONS
Scrapdata(25, "https://www.flipkart.com/search?q=irons&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Water Purifiers
Scrapdata(40, "https://www.flipkart.com/search?q=water+purifier&amp;sid=j9e%2Cabm%2Ci45&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_10_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_10_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=water+purifier%7CWater+purifiers&amp;requestId=b25537f1-0712-4403-a859-ea732c0c0659&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","div","_4rR01T","div","_30jeq3 _1_WHN1","ul","_1xgFaf","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc _27UcVY","div","_2Tpdn3","div","_3Ay6Sb")
# Gromming Kit
Scrapdata(25, "https://www.flipkart.com/health-personal-care-appliances/personal-care-appliances/grooming-kit/pr?sid=zlw%2C79s%2Cbi7&amp;otracker=nmenu_sub_Men_0_Grooming+Kits&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Mobile Accessories
Scrapdata(25, "https://www.flipkart.com/search?q=mobile+accessories&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Desktops PC's
Scrapdata(25, "https://www.flipkart.com/search?q=desktop+pcs&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Gaming Accessories
Scrapdata(25, "https://www.flipkart.com/search?q=gaming+accessories&amp;sid=4rr%2Ckm5&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_17_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_17_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=gaming+accessories%7CGaming+Accessories&amp;requestId=476d5dee-36ca-4eb9-a848-599a9b17d28b&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Computer Accessories
Scrapdata(25, "https://www.flipkart.com/search?q=computer+accessories&amp;sid=6bo%2Cg0i&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_15_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_15_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=computer+accessories%7CComputer+Components&amp;requestId=ae9f518f-8413-4173-83c5-5a518f9e5e99&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Computer Peripherals
Scrapdata(25, "https://www.flipkart.com/search?q=computer+peripherals&amp;sid=6bo%2Ctia&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_13_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_13_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=computer+peripherals%7CComputer+Peripherals&amp;requestId=26406f30-2344-4f25-9f4f-149f53143652&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Smart Home Automation
Scrapdata(25, "https://www.flipkart.com/search?q=smart+home+automation&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Camera
Scrapdata(40, "https://www.flipkart.com/search?q=camera&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","div","_4rR01T","div","_30jeq3 _1_WHN1","ul","_1xgFaf","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc _27UcVY","div","_2Tpdn3","div","_3Ay6Sb")
# Camera Accessories
Scrapdata(25, "https://www.flipkart.com/search?q=camera+accessories&amp;sid=jek%2C6l2&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_17_sc_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_17_sc_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=camera+accessories%7CCamera+Accessories&amp;requestId=fd4edc6b-6bb9-4d63-8cbc-e026d8be48b9&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Network Peripherals
Scrapdata(25, "https://www.flipkart.com/search?q=network+components&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Smart Home Appliances
Scrapdata(25, "https://www.flipkart.com/search?q=small+home+appliances&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Mens footware
Scrapdata(25, "https://www.flipkart.com/search?q=men+footwear&amp;sid=osp%2Ccil%2Ce83&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=men+footwear%7CMen%E2%80%99s+Sandals+%26+Floaters&amp;requestId=b63aac68-b7a0-4fb3-b0a4-b0b4f06a387a&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_2WkVRV","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Men Shirt
Scrapdata(25, "https://www.flipkart.com/search?q=mens+clothing&amp;sid=clo%2Cash&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&amp;as-pos=2&amp;as-type=RECENT&amp;suggestionId=mens+clothing%7CTopwear&amp;requestId=65d780b3-39a5-4cdb-bd84-53e8e0228915&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_2WkVRV","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women wear
Scrapdata(25, "https://www.flipkart.com/search?q=women+&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women ethnic wear
Scrapdata(25, "https://www.flipkart.com/search?q=women+ethnic+wear&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_2WkVRV","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women ethnic bottom
Scrapdata(25, "https://www.flipkart.com/search?q=women+ethnic+bottom&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_2WkVRV","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women footware
Scrapdata(25, "https://www.flipkart.com/search?q=women+shoes&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_2WkVRV","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women watches
Scrapdata(25, "https://www.flipkart.com/search?q=women+smart+watches&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_3eWWd-","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women Electronics
Scrapdata(25, "https://www.flipkart.com/search?q=women+personal+care+appliances&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women Grooming
Scrapdata(25, "https://www.flipkart.com/search?q=women+grooming&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women beauty
Scrapdata(25, "https://www.flipkart.com/search?q=women+beauty&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Jewelery
Scrapdata(25, "https://www.flipkart.com/search?q=women+jewellery+set&amp;sid=mcr%2C96v%2Cyx2&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_11_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_11_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=women+jewellery+set%7CJewellery+Sets&amp;requestId=2168ffa9-952f-4775-ba40-bb9701c4a93f&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa _2-ICcC","div","_30jeq3","div","_2WkVRV-","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Women accessories
Scrapdata(25, "https://www.flipkart.com/search?q=women+accessories&amp;sid=reh%2Cihu&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=women+accessories%7CHandbags+%26+Clutches&amp;requestId=a6899b64-a860-4c6b-aca5-c354b90a68e9&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_2WkVRV","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Kids clothing
Scrapdata(25, "https://www.flipkart.com/clothing-and-accessories/pr?sid=clo&amp;otracker=categorytree&amp;p%5B%5D=facets.ideal_for%255B%255D%3DGirls&amp;p%5B%5D=facets.ideal_for%255B%255D%3DBoys&amp;p%5B%5D=facets.ideal_for%255B%255D%3DBoys%2B%2526%2BGirls&amp;p%5B%5D=facets.ideal_for%255B%255D%3DBaby%2BBoys%2B%2526%2BBaby%2BGirls&amp;p%5B%5D=facets.ideal_for%255B%255D%3DBaby%2BBoys&amp;p%5B%5D=facets.ideal_for%255B%255D%3DBaby%2BGirls&amp;otracker=nmenu_sub_Baby+%26+Kids_0_Kids+Clothing&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_3eWWd-","div","IRpwTa","span","IRpwTa","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Kids Footware
Scrapdata(25, "https://www.flipkart.com/search?q=kids+footware&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","IRpwTa","div","_30jeq3","div","_2WkVRV","div","IRpwTa","span","IRpwTa","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Kids care
Scrapdata(25, "https://www.flipkart.com/search?q=baby+care&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_30jeq3","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_30jeq3")
# Kitchen serveware
Scrapdata(25, "https://www.flipkart.com/search?q=kitchen+cookware+serveware&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Tableware
Scrapdata(25, "https://www.flipkart.com/search?q=tableware+and+dinnerware&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Kitchen storage
Scrapdata(25, "https://www.flipkart.com/search?q=kitchen+storage&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Furniture
Scrapdata(25, "https://www.flipkart.com/search?q=furniture&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Furnishing
Scrapdata(25, "https://www.flipkart.com/search?q=furnishing&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Home lights
Scrapdata(25, "https://www.flipkart.com/search?q=home+lightneinh&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Festive decor
Scrapdata(25, "https://www.flipkart.com/search?q=festive+decor+toran&amp;sid=bro%2Ctez%2Chpt&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_14_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_14_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=festive+decor+toran%7CToran&amp;requestId=47a3f55e-1cb8-47c7-b9f4-b40ea23e7195&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Pet supplies
Scrapdata(40, "https://www.flipkart.com/search?q=pet+supplies&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","div","_4rR01T","div","_30jeq3 _1_WHN1","ul","_1xgFaf","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc _27UcVY","div","_2Tpdn3","div","_3Ay6Sb")
# Christmas
Scrapdata(25, "https://www.flipkart.com/search?q=christmas&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;otracker=nmenu_sub_Home+%26+Furniture_0_Christmas+Store&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","a","s1Q9rs","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Fitness equipment
Scrapdata(25, "https://www.flipkart.com/exercise-fitness/fitness-equipment/fitness-benches/pr?sid=qoc%2Camf%2Co3b&amp;ctx=eyJjYXJkQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7InZhbHVlQ2FsbG91dCI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ2YWx1ZUNhbGxvdXQiLCJpbmZlcmVuY2VUeXBlIjoiVkFMVUVfQ0FMTE9VVCIsInZhbHVlcyI6WyJVcHRvIDgwJSBPZmYiXSwidmFsdWVUeXBlIjoiTVVMVElfVkFMVUVEIn19LCJ0aXRsZSI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ0aXRsZSIsImluZmVyZW5jZVR5cGUiOiJUSVRMRSIsInZhbHVlcyI6WyJGaXRuZXNzIEJlbmNoIl0sInZhbHVlVHlwZSI6Ik1VTFRJX1ZBTFVFRCJ9fSwiaGVyb1BpZCI6eyJzaW5nbGVWYWx1ZUF0dHJpYnV0ZSI6eyJrZXkiOiJoZXJvUGlkIiwiaW5mZXJlbmNlVHlwZSI6IlBJRCIsInZhbHVlIjoiRkJIR0VHM1hHUUNURzg1VCIsInZhbHVlVHlwZSI6IlNJTkdMRV9WQUxVRUQifX19fX0%3D&amp;fm=neo%2Fmerchandising&amp;iid=M_84df9d0c-7955-485c-bd9c-438ac63d6060_1.FRDB9RJBGJE2&amp;ppt=clp&amp;ppn=sports-gear-essentials-store&amp;otracker=dynamic_omu_infinite_Sports%2B%2526%2BFitness%2BEquipment_1_1.dealCard.OMU_INFINITE_FRDB9RJBGJE2&amp;cid=FRDB9RJBGJE2&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Exercise Equipments
Scrapdata(25, "https://www.flipkart.com/search?q=exercise+equipment&amp;sid=qoc%2Camf%2Cvh3&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=exercise+equipment%7CFitness+Kits&amp;requestId=bf004288-7055-43ce-932b-2712e15b8e6e&amp;as-backfill=on&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","a","s1Q9rs","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Books
Scrapdata(25, "https://www.flipkart.com/search?q=exercise+and+fitness&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Stationary
Scrapdata(25, "https://www.flipkart.com/search?q=stationary&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=off&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Auto accessories
Scrapdata(25, "https://www.flipkart.com/search?q=auto+accessories&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","a","s1Q9rs","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Industrial and scientific tools
Scrapdata(25, "https://www.flipkart.com/search?q=industrial+and+scientific+tools&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","a","s1Q9rs","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Music
Scrapdata(25, "https://www.flipkart.com/search?q=music&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Gaming console
Scrapdata(25, "https://www.flipkart.com/search?q=gaming+console&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# Smart Glasses
Scrapdata(25, "https://www.flipkart.com/search?q=smart+glasses&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=","div","_1YokD2 _3Mn1Gg","a","s1Q9rs","div","_30jeq3","div","_3Djpdu","div","_3LWZlK","span","_2_R_DZ","div","_3I9_wc","div","_2Tpdn3","div","_3Ay6Sb")
# ALI EXPRESS
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-phones.html?page=","&g=y&SearchText=phones","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-laptops.html?page=","&g=y&SearchText=laptops","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-computer-desktop.html?page=","&g=y&SearchText=computer+desktop","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-smat-whatch.html?page=","&g=y&SearchText=smat+whatch","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-automotive-and-motocyclr.html?page=","&g=y&SearchText=automotive+and+motocyclr","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-home-and-garden.html?page=","&g=y&SearchText=home+and+garden","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-Men's-Clothing.html?page=","&g=y&SearchText=Men%27s+Clothing","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-Accessories.html?page=","&g=y&SearchText=Accessories","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-Sports-%26-Entertainment.html?page=","&g=y&SearchText=Sports+%26+Entertainment","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-Shoes.html?page=","&g=y&SearchText=Shoes","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-Furniture.html?page=","&g=y&SearchText=Furniture","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-Babies-%26-Kids.html?page=","&g=y&SearchText=Babies+%26+Kids","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-Phones-%26-Telecommunications.html?page=","&g=y&SearchText=Phones+%26+Telecommunications","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-Home-Appliances.html?page=","&g=y&SearchText=Home+Appliances","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")
ScrapData2(60,"https://www.aliexpress.com/w/wholesale-Beauty-%26-Health.html?page=","&g=y&SearchText=Beauty+%26+Health","div","rightContent2023--rightContainer--2abV4r5","div","3.1A USB Fast Phone Charger Adapter 6 In1 Mulit Plug Travel Charger For iPhone 13 12 Samsung Xiaomi QC3.0 Quick Charger","div","multi--price-sale--U-S0jtj","div","s-item__details clearfix","span","clipped","span","s-item__seller-info-text","span","NEGATIVE BOLD","div","s-item__detail s-item__detail--primary","span","s-item__seller-info-text")


df = pd.DataFrame({
    'Product Name': Names,
    'Product Prices': Prices,
    'Product Description': Descriptions,
    'Ratings': Ratings,
    'No. of Ratings and Reviews': NoOFReviews,
    'Discounted Prices': DiscountedPrice,
    'Delivery': Delivery,
    'Discount%': DiscountedPercent
})

df.to_csv('Final.csv', index=False, encoding='utf-8')
driver.quit()




# wait = WebDriverWait(driver, 20)  # Increased waiting time to 20 seconds
#         try:
#             wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, f'{boxtag}.{boxclass}')))
#         except Exception as e:
#             print(f"Error: {e}. Skipping page {i}.")
#             continue
